// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0TJSUzj5TyDi3hnZGaZ5WPyvxWRqtRI',
    appId: '1:935037179293:web:9b8a09496fcd6c43c00b74',
    messagingSenderId: '935037179293',
    projectId: 'sample-28084',
    authDomain: 'sample-28084.firebaseapp.com',
    storageBucket: 'sample-28084.appspot.com',
    measurementId: 'G-LXK2NHGPN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoTXHCslwNVIqofdtNOgtz_-FBceiY5k',
    appId: '1:935037179293:android:186400defba0a01dc00b74',
    messagingSenderId: '935037179293',
    projectId: 'sample-28084',
    storageBucket: 'sample-28084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNR_4H75WhE7tDuCyUiSCYc06mNjXVgzk',
    appId: '1:935037179293:ios:b9f266072d4fa944c00b74',
    messagingSenderId: '935037179293',
    projectId: 'sample-28084',
    storageBucket: 'sample-28084.appspot.com',
    iosClientId: '935037179293-refsmdp69jlovh1q6uuq6l82k3esnao7.apps.googleusercontent.com',
    iosBundleId: 'com.dev.sample',
  );
}
