name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master features]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master features]

  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

     
    
# on: push    # Default will running for every branch.
    
jobs:
  test-analyze:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
   # - run: flutter test
